import { useState } from "react";
import { ShieldCheck } from "lucide-react";

export default function TwoFactorAuthTab() {

      const [otp, setOtp] = useState("");

      const qrCodeUrl =
            "https://api.qrserver.com/v1/create-qr-code/?size=180x180&data=Example2FASetup";


      const handleEnable = () => {

            if (!otp || otp.length !== 6) return;

            console.log("OTP:", otp);

      };


      return (

            <div className="space-y-6 max-w-md">

                  {/* Description */}
                  <div className="space-y-2 text-sm text-gray-600">

                        <p>
                              Use an authenticator app (Google Authenticator, Microsoft Authenticator, etc.)
                              to scan this QR code.
                        </p>

                        <p>
                              After scanning, enter the 6-digit code generated by the app.
                        </p>

                  </div>



                  {/* QR Code */}
                  <div className="
        border border-gray-200
        rounded-lg p-4
        w-fit bg-gray-50
      ">

                        <img
                              src={qrCodeUrl}
                              alt="QR Code"
                              className="w-44 h-44"
                        />

                  </div>



                  {/* OTP Input */}
                  <div>

                        <label className="block text-sm text-gray-600 mb-1">

                              Enter OTP code

                        </label>

                        <input
                              value={otp}
                              onChange={(e) => setOtp(e.target.value)}
                              maxLength={6}
                              placeholder="Enter 6-digit code"
                              className="
            w-64 px-4 py-2.5 text-sm
            border border-gray-200 rounded-lg
            focus:outline-none focus:ring-2 focus:ring-orange-400
            tracking-widest
          "
                        />

                  </div>



                  {/* Enable Button */}
                  <button
                        onClick={handleEnable}
                        className="
          flex items-center gap-2
          bg-orange-500 hover:bg-orange-600
          text-white text-sm font-medium
          px-5 py-2.5 rounded-lg
          transition-colors
        "
                  >

                        <ShieldCheck size={16} />

                        Enable 2FA Authentication

                  </button>


            </div>

      );

}